# Generated by Django 6.0.4 on 2026-04-16 13:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_book_genre_book_summary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="summary",
            new_name="ai_summary",
        ),
        migrations.RemoveField(
            model_name="book",
            name="url",
        ),
        migrations.AddField(
            model_name="book",
            name="book_url",
            field=models.URLField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="cover_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="review_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="sentiment",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name="BookChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_text", models.TextField()),
                ("chunk_index", models.IntegerField()),
                ("embedding_id", models.CharField(max_length=255)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="books.book",
                    ),
                ),
            ],
        ),
    ]
